#! /usr/local/bin/bash

#sxhkd &

### Abkürzungen einiger Befehle
# bspc
_bc() {
	bspc config "$@"
}

# check if a command exists ONLY then do the command
_check() {
	command -v "$1" > /dev/null
}



bspc monitor -d I II III IV V VI VII VIII IX X

_bc border_width 4
_bc window_gap 12
_bc split_ratio 0.50
_bc borderless_monocle false
_bc gapless_monocle true
_bc focus_follows_pointer true
_bc pointer_follows_monitor true

# colors
_bc normal_border_color "#312e30"
_bc active_border_color "#b1942b"
_bc focused_border_color "#e63e20"
_bc presel_feedback_color "#2a2829"


# small compositor
_check xcompmgr && xcompmgr -cCfF -t -2 -l -2 -r 2.8 -o 0.55 -D 5 &

# wallpaper
_check feh && ~/.fehbg &


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a chrome desktop='^2'
bspc rule -a mpv state=floating
