set PATH ~/bin:$PATH
alias yys 'xbps-query -Rs'
alias yyi 'sudo xbps-install'
alias yyr 'sudo xbps-remove'
alias yyu 'sudo xbps-install -Su'
alias yyl 'xbps-query -l | most'
alias yyc 'sudo xbps-remove -o'
alias yycc 'sudo xbps-remove -O'
alias qqq 'sudo poweroff'
alias zzz 'sudo pm-suspend'
